name: Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore VaultFlower.sln

      - name: Build solution
        run: dotnet build VaultFlower.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test VaultFlower.sln --no-build --configuration Release --verbosity normal
